services:
  db:
    # We use a mariadb image which supports both amd64 & arm64 architecture
    image: mariadb:10.5-focal
    # image: mariadb:10.6.4-focal
    # If you really want to use MySQL, uncomment the following line
    # image: mysql:8.0.27
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - next-backend-volume:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=nextbe01
      - MYSQL_USER=root
      - MYSQL_PASSWORD=pass
    ports:
      - 3306:3306

volumes:
  next-backend-volume:
